export enum CityNameEnum {
  CHANDIGARH = 1,
  DELHI = 2,
  MUMBAI = 3,
  PUNE = 4,
  AHMEDABAD = 5,
  JAIPUR = 6,
  CHENNAI = 7,
  PANAJI = 8,
  LUDHIANA = 9,
  GURUGRAM = 10,
  FARIDABAD = 11,
  KOCHI = 12,
  LUCKNOW = 13,
  GUWAHATI = 14,
  BENGALURU = 15,
  HYDERABAD = 16
}
